apiVersion: v1
kind: Service
metadata:
  name: restapp
spec:
  type: LoadBalancer
  selector:
    app: restapp
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restapp
spec:
  selector:
    matchLabels:
      app: restapp
  template:
    metadata:
      labels:
        app: restapp
    spec:
      containers:
      - name: restapp
        image: 874242096105.dkr.ecr.us-east-2.amazonaws.com/restapp:1.0
        resources:
          limits:
            memory: "512Mi"
          requests:
            memory: "512Mi"
        ports:
        - containerPort: 8080
